name: Recover Secrets
on: workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Base64 Encode Passwords to Log
        env:
          K_PASS: ${{ secrets.KEYSTORE_PASSWORD }}
          K_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "KEYSTORE_PASSWORD (Base64):"
          echo "$K_PASS" | base64
          
          echo "KEY_ALIAS (Base64):"
          echo "$K_ALIAS" | base64

      - name: Save Keystore to File
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" > keystore_base64.txt

      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: recovered-keystore
          path: keystore_base64.txt
